CREATE TABLE F_LIVE (
	LIVE_KEY_ID int NOT NULL AUTO_INCREMENT,
	DATETIME DATETIME NOT NULL UNIQUE,
	DAY_KEY_ID int NOT NULL,
	TEMP_C numeric,
	PRESS_Pa numeric,
	HUMIDITY_PERC numeric,
	HUMIDITY_SOIL varchar(255),
	RAIN_SINCE_LAST_READING_MM numeric NOT NULL,
	PRIMARY KEY (LIVE_KEY_ID)
);

CREATE TABLE D_DAY (
	DAY_KEY_ID int NOT NULL AUTO_INCREMENT,
	DAY_DATETIME DATETIME NOT NULL UNIQUE,
	DAY_YYYYMMDD int NOT NULL,
	WEEKDAY_NUM int NOT NULL,
	WEEKDAY_NAME varchar(255) NOT NULL,
	WEEKDAY_NOMBRE varchar(255) NOT NULL,
	PRIMARY KEY (DAY_KEY_ID)
);

CREATE TABLE F_HOUR (
	HOUR_KEY_ID int NOT NULL AUTO_INCREMENT,
	DATETIME DATETIME NOT NULL UNIQUE,
	DAY_KEY_ID int NOT NULL,
	TEMP_C numeric,
	PRESS_Pa numeric,
	HUMIDITY_PERC numeric,
	HUMIDITY_SOIL varchar(255),
	RAIN_SINCE_LAST_READING_MM numeric,
	PRIMARY KEY (HOUR_KEY_ID)
);

ALTER TABLE F_LIVE ADD CONSTRAINT F_LIVE_fk0 FOREIGN KEY (DAY_KEY_ID) REFERENCES D_DAY(DAY_KEY_ID);

ALTER TABLE F_HOUR ADD CONSTRAINT F_HOUR_fk0 FOREIGN KEY (DAY_KEY_ID) REFERENCES D_DAY(DAY_KEY_ID);

